<a href="https://colab.research.google.com/github/YuvikaSingodia10/AI-Data-Science-2026/blob/main/01-foundation-revision/Day02_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'Yes':[50,21] , 'No':[131,21]})

   Yes   No
0   50  131
1   21   21

In [3]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'],
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [4]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
from google.colab import files
wine_reviews = files.upload()

Saving winemag-data-130k-v2.csv.zip to winemag-data-130k-v2.csv (1).zip

In [15]:
import zipfile
import os

# Unzip the uploaded file
zip_path = '/content/winemag-data-130k-v2.csv.zip'
if not os.path.exists(zip_path):
    zip_path = '/content/winemag-data-130k-v2.csv (1).zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/')

# Now read the extracted CSV file
wine_reviews = pd.read_csv('/content/winemag-data-130k-v2.csv', index_col=0)
display(wine_reviews.head())

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [16]:
wine_reviews.shape
wine_reviews.head()
wine_reviews.tail()
wine_reviews.info()
wine_reviews.describe()
wine_reviews.columns
wine_reviews.index

<class 'pandas.core.frame.DataFrame'>
Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)

In [2]:
from google.colab import files
uploads = files.upload()

Saving winemag-data-130k-v2.csv to winemag-data-130k-v2.csv

In [5]:
# Read the uploaded CSV file into a pandas DataFrame
import pandas as pd
wine_data = pd.read_csv('winemag-data-130k-v2.csv', index_col=0)
wine_data.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Neha"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 92, 78, 88]
})

print(df)

    Name  Age  Marks
0   Aman   20     85
1   Riya   21     92
2  Karan   19     78
3   Neha   22     88

In [2]:
df["Name"]

0     Aman
1     Riya
2    Karan
3     Neha
Name: Name, dtype: object

In [3]:
#loc is used for label based indexing
df.loc[0]

Name     Aman
Age        20
Marks      85
Name: 0, dtype: object

In [4]:
df.loc[1:3]

    Name  Age  Marks
1   Riya   21     92
2  Karan   19     78
3   Neha   22     88

In [5]:
# iloc is used for position based indexing or we can say that index based indexing

df.iloc[0]

Name     Aman
Age        20
Marks      85
Name: 0, dtype: object

In [9]:
df.iloc[1:3]

    Name  Age  Marks
1   Riya   21     92
2  Karan   19     78

In [12]:
# Reset the index first if 'Name' is already the index to make this cell repeatable
if 'Name' not in df.columns:
    df = df.reset_index()

df = df.set_index("Name")
df

       Age  Marks
Name
Aman    20     85
Riya    21     92
Karan   19     78
Neha    22     88

In [17]:
#conditional selection

df["Marks" ]> 85

df[df["Marks"] > 85]

      Age  Marks
Name
Riya   21     92
Neha   22     88

In [ ]:
# multiple condition
df[(df["Age"] > 20) & (df["Marks"] > 85)]

In [21]:
#####################-----------NUMPY--------------------------

import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr.mean())
print(arr.max())
print(arr.sum())

25.0
40
100

In [23]:
# 2d array in nummpy
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

[[1 2 3]
 [4 5 6]]

In [24]:
#shape → rows & columns
#ndim  → number of dimensions
#size  → total elements

arr.shape
print(arr)

arr.ndim
print(arr)

arr.size
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]

In [28]:
#slicing in array
arr = np.array([10, 20, 30, 40, 50])

arr = arr[2:4]
print(arr)

print(arr * 2)

[30 40]
[60 80]

In [30]:
# statical funtion in numpy
arr = np.array([10, 20, 30, 40, 50])
print(arr.mean())
print(arr.max())
print(arr.sum())
print(np.median(arr))

30.0
50
150
30.0

In [31]:
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]